---
# ansible playbook

- hosts: raspberries
  roles:
    - locale
    - essentials
    - dyn_dns
    - nextcloud
  vars:
    home: '{{ ansible_env.HOME }}'
    user: '{{ ansible_env.USER }}'
  vars_files:
    - vars/default.yml
    - 'vars/private/{{ inventory_hostname }}.yml'
