---
- hosts: lanberries
  roles:
    - locale
    - essentials
    - dyn_dns
    - nextcloud
  vars:
    home: '{{ ansible_env.HOME }}'
    user: '{{ ansible_env.USER }}'

- hosts: wifiberries
  roles:
    - locale
    - essentials
    - shairport-sync
  vars:
    home: '{{ ansible_env.HOME }}'
    user: '{{ ansible_env.USER }}'
