---
- name: install basic packages
  apt:
    state: present
    pkg:
      - git
      - certbot
      - unzip
      - curl
      - libcurl4
      - ffmpeg
  become: yes
  tags: packages

- name: install web services
  apt:
    state: present
    pkg:
      - nginx
      - postgresql
      - redis-server
  become: yes
  tags: packages

- name: install php packages
  apt:
    state: present
    pkg:
      - php7.3-fpm
      - php7.3-curl
      - php7.3-gd
      - php7.3-intl
      - php7.3-mbstring
      - php7.3-xml
      - php7.3-zip
      - php7.3-apcu
      - php7.3-pgsql
      - php7.3-json
      - php7.3-bz2
      - php-imagick
      - php-redis
  become: yes
  tags: packages
