---
- name: encrypt wifi password
  command: 'wpa_passphrase {{ wifi.name }} {{ wifi.password }}'
  register: wifi_config
  become: yes
  tags: wifi

- name: extract encrypted password
  set_fact:
    encrypted_wifi_password: "{{ wifi_config.stdout | regex_replace('((.|\\s)*psk=)|\\s}', '')}}"
  tags: wifi

- name: insert config
  template:
    src: wpa_supplicant.conf.j2
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
  become: yes
  tags: wifi

- name: reload wifi config
  command: wpa_cli -i wlan0 reconfigure
  become: yes
  tags: wifi
