---
- name: Configure caching
  ansible.builtin.template:
    src: config/cache.config.php.j2
    dest: /var/www/nextcloud/config/cache.config.php
    owner: www-data
    group: www-data
    mode: "644"
  become: true
  tags: [nextcloud, config, php]

- name: Configure data directory
  ansible.builtin.template:
    src: config/data.config.php.j2
    dest: /var/www/nextcloud/config/data.config.php
    owner: www-data
    group: www-data
    mode: "644"
  become: true
  tags: [nextcloud, config, php]

- name: Configure database
  ansible.builtin.template:
    src: config/database.config.php.j2
    dest: /var/www/nextcloud/config/database.config.php
    owner: www-data
    group: www-data
    mode: "644"
  become: true
  tags: [nextcloud, config, php]

- name: Configure email server
  ansible.builtin.template:
    src: config/email.config.php.j2
    dest: /var/www/nextcloud/config/email.config.php
    owner: www-data
    group: www-data
    mode: "644"
  become: true
  tags: [nextcloud, config, php]
