---
- name: configure caching
  template:
    src: config/cache.config.php.j2
    dest: /var/www/nextcloud/config/cache.config.php
    owner: www-data
    group: www-data
  become: yes
  tags: [nextcloud, config, php]

- name: configure data directory
  template:
    src: config/data.config.php.j2
    dest: /var/www/nextcloud/config/data.config.php
    owner: www-data
    group: www-data
  become: yes
  tags: [nextcloud, config, php]

- name: configure database
  template:
    src: config/database.config.php.j2
    dest: /var/www/nextcloud/config/database.config.php
    owner: www-data
    group: www-data
  become: yes
  tags: [nextcloud, config, php]

- name: configure email server
  template:
    src: config/email.config.php.j2
    dest: /var/www/nextcloud/config/email.config.php
    owner: www-data
    group: www-data
  become: yes
  tags: [nextcloud, config, php]
