---
- name: Enable APCu for Nextcloud cron jobs
  ini_file:
    path: '/etc/php/{{ php_version }}/mods-available/apcu.ini'
    section: ''
    option: apc.enable_cli
    value: 1
  become: yes
  notify:
    - restart nginx
  tags: [nextcloud, cron, php]

- name: add nextcloud cron service
  template:
    src: systemd/nextcloudcron.service.j2
    dest: /etc/systemd/system/nextcloudcron.service
  become: yes
  tags: [nextcloud, cron, systemd]

- name: add nextcloud cron timer
  template:
    src: systemd/nextcloudcron.timer.j2
    dest: /etc/systemd/system/nextcloudcron.timer
  become: yes
  tags: [nextcloud, cron, systemd]

- name: start nextcloud cron timer
  systemd:
    name: nextcloudcron.timer
    state: started
    enabled: yes
  become: yes
  tags: [nextcloud, cron, systemd]
