---
- name: Enable APCu for Nextcloud cron jobs
  community.general.ini_file:
    path: '/etc/php/{{ php_version }}/mods-available/apcu.ini'
    section: ''
    option: apc.enable_cli
    value: 1
  become: true
  notify:
    - restart nginx
  tags: [nextcloud, cron, php]

- name: Add nextcloud cron service
  ansible.builtin.template:
    src: systemd/nextcloudcron.service.j2
    dest: /etc/systemd/system/nextcloudcron.service
  become: true
  tags: [nextcloud, cron, systemd]

- name: Add nextcloud cron timer
  ansible.builtin.template:
    src: systemd/nextcloudcron.timer.j2
    dest: /etc/systemd/system/nextcloudcron.timer
  become: true
  tags: [nextcloud, cron, systemd]

- name: Start nextcloud cron timer
  ansible.builtin.systemd:
    name: nextcloudcron.timer
    state: started
    enabled: true
  become: true
  tags: [nextcloud, cron, systemd]
