---
- name: add nextcloud cron service
  template:
    src: systemd/nextcloudcron.service.j2
    dest: /etc/systemd/system/nextcloudcron.service
  become: yes
  tags: [nextcloud, cron, systemd]

- name: add nextcloud cron timer
  template:
    src: systemd/nextcloudcron.timer.j2
    dest: /etc/systemd/system/nextcloudcron.timer
  become: yes
  tags: [nextcloud, cron, systemd]

- name: start nextcloud cron timer
  systemd:
    name: nextcloudcron.timer
    state: started
    enabled: yes
  become: yes
  tags: [nextcloud, cron, systemd]
