---
- name: Create mount directory
  ansible.builtin.file:
    path: /hdd
    state: directory
    owner: '{{ user }}'
    group: '{{ user }}'
  become: true
  tags: [nextcloud, harddrive]

- name: Mount hdd
  ansible.posix.mount:
    path: /hdd
    src: /dev/sda1
    fstype: ext4
    state: present
  become: true
  tags: [nextcloud, harddrive]

- name: Add nextcloud directory
  ansible.builtin.file:
    path: /hdd/nextcloud/
    owner: www-data
    group: www-data
    state: directory
  become: true
  tags: [nextcloud, harddrive]
