---
- name: stop nginx (to free ports)
  service:
    name: nginx
    state: stopped
  become: yes
  tags: [nextcloud, ssl]

- name: add certificate
  command: certbot certonly -d {{ pi.domain }} --email {{ ssl.email }} --standalone --noninteractive --agree-tos
  args:
    creates: '/etc/letsencrypt/live/{{ pi.domain }}'
  become: yes
  tags: [nextcloud, ssl]

- name: add config for nextcloud page
  template:
    src: nginx/nextcloud.config.j2
    dest: /etc/nginx/sites-enabled/nextcloud
  become: yes
  tags: [nextcloud, ssl]

- name: start nginx again
  service:
    name: nginx
    state: started
  become: yes
  tags: [nextcloud, ssl]

- name: add certbot renewal service
  template:
    src: systemd/certbot_renewal.service.j2
    dest: /etc/systemd/system/certbot_renewal.service
  become: yes
  tags: [nextcloud, ssl, systemd]

- name: add certbot renewal timer
  template:
    src: systemd/certbot_renewal.timer.j2
    dest: /etc/systemd/system/certbot_renewal.timer
  become: yes
  tags: [nextcloud, ssl, systemd]

- name: start certbot renewal timer
  systemd:
    name: certbot_renewal.timer
    state: started
    enabled: yes
  become: yes
  tags: [nextcloud, ssl, systemd]

