---
- name: stop nginx (to free ports)
  service:
    name: nginx
    state: stopped
  become: yes
  tags: [nextcloud, ssl]

- name: add certificate
  command: certbot certonly -d {{pi.domain}} --email {{ssl.email}} --standalone --noninteractive --agree-tos
  args:
    creates: '/etc/letsencrypt/live/{{ pi.domain }}'
  become: yes
  tags: [nextcloud, ssl]

- name: add config for nextcloud page
  template:
    src: nginx/nextcloud.config.j2
    dest: /etc/nginx/sites-enabled/nextcloud
  become: yes
  tags: [nextcloud, ssl]

- name: start nginx again
  service:
    name: nginx
    state: started
  become: yes
  tags: [nextcloud, ssl]

# TODO: add service to renew certificate
# (only works when port 80 and 443 free to the internet)
