---
- name: download nextcloud
  get_url:
    url: "{{ nextcloud_com.releases_url }}-{{ nextcloud_com.version }}.tar.bz2"
    checksum: "sha256:{{ nextcloud_com.releases_url }}-{{ nextcloud_com.version }}.tar.bz2.sha256"
    dest: "{{ home }}"
  check_mode: no
  register: nextcloud_archive
  notify:
    - extract nextcloud files into www
  tags: [nextcloud, installation]

- name: flush handlers
  meta: flush_handlers
  tags: [nextcloud, installation]

- name: check if nextcloud directory already exists
  stat:
    path: /var/www/nextcloud
  register: nextcloud_dir
  tags: [nextcloud, installation]

- debug:
    msg: nextcloud directory already exists
  when: nextcloud_dir.stat.exists
  tags: [nextcloud, installation]
