---
- name: install packages
  import_tasks: packages.yml

- name: set up harddrive
  import_tasks: harddrive.yml

- name: install nextcloud
  import_tasks: install.yml

- name: setup db
  import_tasks: postgres.yml

- name: setup nginx
  import_tasks: nginx.yml

- name: configure php
  import_tasks: php.yml

- name: configure nextcloud installation
  import_tasks: config.yml
