---
- name: Install packages
  ansible.builtin.import_tasks: packages.yml

- name: Install nextcloud
  ansible.builtin.import_tasks: install.yml

- name: Set up harddrive
  ansible.builtin.import_tasks: harddrive.yml

- name: Configure nextcloud installation
  ansible.builtin.import_tasks: config.yml

- name: Configure php
  ansible.builtin.import_tasks: php.yml

- name: Setup db
  ansible.builtin.import_tasks: postgres.yml

- name: Setup nginx
  ansible.builtin.import_tasks: nginx.yml

- name: Setup cronjobs
  ansible.builtin.import_tasks: cron.yml

- name: Setup ssl certificates
  ansible.builtin.import_tasks: https.yml
