---
- name: add http only config for nextcloud page
  template:
    src: nginx/nextcloud_http.config.j2
    dest: /etc/nginx/sites-enabled/nextcloud
  become: yes
  when: https_only == false
  tags: [nextcloud, nginx]

- name: disable default page
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: yes
  tags: [nextcloud, nginx]

- name: move config for default page
  template:
    src: nginx/default.config.j2
    dest: /etc/nginx/sites-available/default
  tags: [nextcloud, nginx]

- name: reload nginx
  service:
    name: nginx
    state: reloaded
  become: yes
  tags: [nextcloud, nginx]
