---
- name: Check live certificate directory
  ansible.builtin.stat:
    path: '/etc/letsencrypt/live/{{ pi.domain }}'
  become: true
  register: ssl_dir
  tags: [nextcloud, nginx]

- name: Add http only config for nextcloud page
  ansible.builtin.template:
    src: nginx/nextcloud_http.config.j2
    dest: /etc/nginx/sites-enabled/nextcloud
    mode: "644"
  become: true
  notify:
    - reload nginx
  when: ssl_dir.stat.isdir is not defined or not ssl_dir.stat.isdir
  tags: [nextcloud, nginx]

- name: Disable default page
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: true
  tags: [nextcloud, nginx]

- name: Move config for default page
  ansible.builtin.template:
    src: nginx/default.config.j2
    dest: /etc/nginx/sites-available/default
    mode: "644"
  become: true
  tags: [nextcloud, nginx]
