---
- name: install basic packages
  apt:
    state: present
    pkg:
      - git
      - certbot
      - unzip
      - curl
      - libcurl4
      - ffmpeg
      - libmagickcore-6.q16-3-extra
  become: yes
  tags: [nextcloud, packages]

- name: install dev packages
  apt:
    state: present
    pkg: python3-psycopg2
  become: yes
  tags: [nextcloud, packages, postgres]

- name: install web services
  apt:
    state: present
    pkg:
      - nginx
      - postgresql
  become: yes
  tags: [nextcloud, packages]

- name: install php packages
  apt:
    state: present
    pkg:
      - 'php{{ php_version }}-fpm'
      - 'php{{ php_version }}-curl'
      - 'php{{ php_version }}-gd'
      - 'php{{ php_version }}-intl'
      - 'php{{ php_version }}-mbstring'
      - 'php{{ php_version }}-xml'
      - 'php{{ php_version }}-zip'
      - 'php{{ php_version }}-apcu'
      - 'php{{ php_version }}-pgsql'
      - 'php{{ php_version }}-json'
      - 'php{{ php_version }}-bz2'
      - 'php{{ php_version }}-bcmath'
      - 'php{{ php_version }}-gmp'
      - php-imagick
  become: yes
  tags: [nextcloud, packages]
