---
- name: Install basic packages
  ansible.builtin.apt:
    state: present
    pkg:
      - git
      - certbot
      - unzip
      - curl
      - libcurl4
      - ffmpeg
      - libmagickcore-6.q16-3-extra
  become: true
  tags: [nextcloud, packages]

- name: Install dev packages
  ansible.builtin.apt:
    state: present
    pkg: python3-psycopg2
  become: true
  tags: [nextcloud, packages, postgres]

- name: Install web services
  ansible.builtin.apt:
    state: present
    pkg:
      - nginx
      - postgresql
  become: true
  tags: [nextcloud, packages]

- name: Install php packages
  ansible.builtin.apt:
    state: present
    pkg:
      - 'php{{ php_version }}-fpm'
      - 'php{{ php_version }}-curl'
      - 'php{{ php_version }}-gd'
      - 'php{{ php_version }}-intl'
      - 'php{{ php_version }}-mbstring'
      - 'php{{ php_version }}-xml'
      - 'php{{ php_version }}-zip'
      - 'php{{ php_version }}-apcu'
      - 'php{{ php_version }}-pgsql'
      - 'php{{ php_version }}-json'
      - 'php{{ php_version }}-bz2'
      - 'php{{ php_version }}-bcmath'
      - 'php{{ php_version }}-gmp'
      - php-imagick
  become: true
  tags: [nextcloud, packages]

- name: Install acl filesystem for unprivileged users
  ansible.builtin.apt:
    state: present
    pkg: acl
  become: true
  tags: [nextcloud, packages]
