---
- name: change password for postgres user
  postgresql_user:
    db: postgres
    user: postgres
    password: '{{ postgres.postgres_user_password }}'
  become_user: postgres
  become: yes
  vars:
    ansible_ssh_pipelining: true
  tags: [nextcloud, postgres]

- name: create nextcloud database user
  postgresql_user:
    user: '{{ postgres.nextcloud.db_user }}'
    password: '{{ postgres.nextcloud.db_password }}'
    role_attr_flags: CREATEDB
  become_user: postgres
  become: yes
  vars:
    ansible_ssh_pipelining: true
  tags: [nextcloud, postgres]

- name: create nextcloud database
  postgresql_db:
    name: '{{ postgres.nextcloud.db_name }}'
    owner: '{{ postgres.nextcloud.db_user }}'
  become_user: postgres
  become: yes
  vars:
    ansible_ssh_pipelining: true
  tags: [nextcloud, postgres]

