---
- name: Retrieve Postgres version
  community.postgresql.postgresql_info:
    filter: ver*
  register: postgres_info_result
  become: true
  become_user: postgres
  tags: [nextcloud, postgres]

- name: Debug Postgres version
  ansible.builtin.debug:
    msg: 'Running Postgres version: {{ postgres_info_result.version.major }}'
  tags: [nextcloud, postgres]
  when: postgres_info_result.version.major is defined

- name: Set all user authentication method to md5
  community.postgresql.postgresql_pg_hba:
    dest: '/etc/postgresql/{{ postgres_info_result.version.major }}/main/pg_hba.conf'
    contype: local
    databases: all
    users: all
    method: md5
  become: true
  notify:
    - restart postgres
  tags: [nextcloud, postgres]

- name: Change password for postgres user
  community.postgresql.postgresql_user:
    db: postgres
    user: postgres
    password: '{{ postgres.postgres_user_password }}'
  become_user: postgres
  become: true
  vars:
    ansible_ssh_pipelining: true
  tags: [nextcloud, postgres]

- name: Create user for Nextcloud database
  community.postgresql.postgresql_user:
    user: '{{ postgres.nextcloud.db_user }}'
    password: '{{ postgres.nextcloud.db_password }}'
    role_attr_flags: CREATEDB
  become_user: postgres
  become: true
  vars:
    ansible_ssh_pipelining: true
  tags: [nextcloud, postgres]

- name: Create database for Nextcloud
  community.postgresql.postgresql_db:
    name: '{{ postgres.nextcloud.db_name }}'
    owner: '{{ postgres.nextcloud.db_user }}'
  become_user: postgres
  become: true
  vars:
    ansible_ssh_pipelining: true
  tags: [nextcloud, postgres]
