---
- name: Add spocon repository to packages list
  ansible.builtin.apt_repository:
    repo: deb http://ppa.launchpad.net/spocon/spocon/ubuntu bionic main
    state: present
    filename: spocon
  become: true
  tags: spotify

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true
  tags: spotify

- name: Install spocon package
  ansible.builtin.apt:
    pkg: spocon
    state: latest
  become: true
  tags: spotify

- name: Configure spocon name
  community.general.ini_file:
    path: /opt/spocon/config.toml
    section: null
    option: deviceName
    value: '"{{ inventory_hostname }}"'
  become: true
  notify:
    - restart spocon
  tags: spotify

- name: Configure spocon mixer backend
  community.general.ini_file:
    path: /opt/spocon/config.toml
    section: player
    option: "\tmixerSearchKeywords"
    value: '""'
  become: true
  notify:
    - restart spocon
  tags: spotify
