---
- name: extract nextcloud files into www
  unarchive:
    src: "{{ nextcloud_archive.dest }}"
    dest: /var/www/
    owner: www-data
    group: www-data
    remote_src: yes
  become: yes

- name: reload nginx
  service:
    name: nginx
    state: reloaded
  become: yes

- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: yes

- name: restart php-fpm
  service:
    name: 'php{{ php_version }}-fpm'
    state: restarted
  become: yes
