---
- name: Extract nextcloud files into www
  ansible.builtin.unarchive:
    src: "{{ nextcloud_archive.dest }}"
    dest: /var/www/
    owner: www-data
    group: www-data
    remote_src: true
  become: true

- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  become: true

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  become: true

- name: Restart php-fpm
  ansible.builtin.service:
    name: 'php{{ php_version }}-fpm'
    state: restarted
  become: true

- name: Restart postgres
  ansible.builtin.service:
    name: postgresql
    state: restarted
  become: true
