---
- name: Uninstall shairport-sync package
  apt:
    state: absent
    pkg: shairport-sync
  become: yes
  tags: [shairport-sync, packages]

- name: Set alsa volume to 100%
  raw: amixer set 'Headphone' 100%
  tags: [shairport-sync]

- name: Remove shairport-sync config
  ansible.builtin.file:
    path: /etc/shairport-sync.conf
    state: absent
  become: yes
  tags: [shairport-sync]

- name: Remove shairport-sync service
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  loop:
    - '/etc/systemd/system/shairport-sync.service'
    - '/etc/systemd/user/shairport-sync.service'
    - '/lib/systemd/system/shairport-sync.service'
    - '/lib/systemd/user/shairport-sync.service'
    - '/etc/init.d/shairport-sync'
  become: yes
  tags: [shairport-sync]
