---
- name: Set alsa volume to 100%
  ansible.builtin.raw: amixer set 'Headphone' 100%
  tags: [shairport-sync]

- name: Install necessary libraries
  ansible.builtin.apt:
    pkg:
      - build-essential
      - git
      - autoconf
      - automake
      - libtool
      - libpopt-dev
      - libconfig-dev
      - libasound2-dev
      - avahi-daemon
      - libavahi-client-dev
      - libssl-dev
      - libsoxr-dev
      - libplist-dev
      - libsodium-dev
      - libavutil-dev
      - libavcodec-dev
      - libavformat-dev
      - uuid-dev
      - libgcrypt-dev
      - xxd
    state: present
    install_recommends: false
  become: true
  tags: [shairport-sync, packages]

- name: Clone nqptp repo
  ansible.builtin.git:
    repo: 'https://github.com/mikebrady/nqptp.git'
    dest: "{{ home }}/nqptp"
    clone: true
    update: true
  tags: [shairport-sync, nqptp]

- name: Configure nqptp installation
  ansible.builtin.shell:
    cmd: autoreconf -fi && ./configure --with-systemd-startup
    chdir: "{{ home }}/nqptp/"
  tags: [shairport-sync, nqptp]

- name: Prepare nqptp installation
  community.general.make:
    chdir: "{{ home }}/nqptp/"
  tags: [shairport-sync, nqptp]

- name: Install nqptp
  community.general.make:
    chdir: nqptp
    target: install
  become: true
  tags: [shairport-sync, nqptp]

- name: Enable nqptp service
  ansible.builtin.systemd:
    name: nqptp
    enabled: true
  become: true
  tags: [shairport-sync, nqptp, systemd]

- name: Start nqptp service
  ansible.builtin.systemd:
    name: nqptp
    state: started
  become: true
  tags: [shairport-sync, nqptp, systemd]

- name: Clone shairport-sync repo
  ansible.builtin.git:
    repo: 'https://github.com/mikebrady/shairport-sync.git'
    dest: "{{ home }}/shairport-sync"
    clone: true
    update: true
  tags: [shairport-sync]

- name: Configure shairport-sync installation
  ansible.builtin.shell:
    cmd: |
      autoreconf -fi && ./configure --sysconfdir=/etc \
                                    --with-alsa \
                                    --with-soxr \
                                    --with-avahi \
                                    --with-ssl=openssl \
                                    --with-systemd \
                                    --with-airplay-2
    chdir: "{{ home }}/shairport-sync/"
  tags: [shairport-sync]

- name: Prepare shairport-sync installation
  community.general.make:
    chdir: "{{ home }}/shairport-sync/"
  tags: [shairport-sync]

- name: Install shairport-sync
  community.general.make:
    chdir: shairport-sync
    target: install
  become: true
  tags: [shairport-sync]

- name: Configure shairport-sync
  ansible.builtin.template:
    src: shairport-sync.conf
    dest: /etc/shairport-sync.conf
  become: true
  notify:
    - restart shairport-sync
  tags: [shairport-sync]

- name: Start shairport-sync service
  ansible.builtin.systemd:
    name: shairport-sync
    state: started
    enabled: true
    daemon_reload: true
  become: true
  tags: [shairport-sync, systemd]

- name: Turn off power management for wifi
  ansible.builtin.command: iwconfig wlan0 power off
  become: true
  tags: [shairport-sync, wifi]
