---
- name: Install shairport-sync package
  apt:
    state: present
    pkg: shairport-sync
  become: yes
  tags: [shairport-sync, packages]

- name: Set alsa volume to 100%
  raw: amixer set 'Headphone' 100%
  tags: [shairport-sync]

- name: Configure shairport-sync
  template:
    src: shairport-sync.conf
    dest: /etc/shairport-sync.conf
  become: yes
  notify:
    - restart shairport-sync
  tags: [shairport-sync]

- name: Start shairport-sync service
  systemd:
    name: shairport-sync
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes
  notify:
    - reboot pi
  tags: [shairport-sync, systemd]
