- name: install dyn dns client
  apt:
    state: present
    pkg:
      - ddclient
      - libio-socket-ssl-perl
  become: yes
  tags: [dns]

- name: add dyn dns client config
  template:
    src: ddclient.conf.j2
    dest: /etc/ddclient.conf
  register: ddclient_config
  become: yes
  tags: [dns]

- name: restart ddclient deamon
  service:
    name: ddclient
    state: restarted
  when: ddclient_config.changed
  become: yes
  tags: [dns]

