---
- name: Install dyn dns client
  ansible.builtin.apt:
    state: present
    pkg:
      - ddclient
      - libio-socket-ssl-perl
  become: true
  tags: [dns]

- name: Add dyn dns client config
  ansible.builtin.template:
    src: ddclient.conf.j2
    dest: /etc/ddclient.conf
    mode: "600"
  notify:
    - restart ddclient deamon
  become: true
  tags: [dns]
