#!/usr/bin/env bash

# NOTE: this is skipping "update" tasks by default.
# Setting up SSL certificates requires a running HTTP server.

set -o errexit
set -o pipefail
set -o nounset

SCRIPTDIR=$(cd "$(dirname "$0")"; pwd)
cd "$SCRIPTDIR/.."

exec ansible-playbook \
  --inventory=raspberries \
  --skip-tags "update" \
  base.yml \
  "$@"
