#!/usr/bin/env bash

function has() {
    type "$1" >/dev/null 2>&1
}

function info() {
    local message=$1
    echo -e "\033[1;37m› $message\033[0m" >&2
}

function abort() {
    local message=$1
    echo -e "\033[1;31m› $message\033[0m" >&2
    exit 1
}
