#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

SCRIPTDIR=$(cd "$(dirname "$0")"; pwd)

# shellcheck source=SCRIPTDIR/lib/helpers
source "$SCRIPTDIR/lib/helpers"

cd "$SCRIPTDIR/.."

has ansible-lint || abort "Requires ansible-lint (pip3 install ansible-lint)"

ansible-lint playbook.yaml
