---
- name: add hostname file
  template:
    src: hostname.j2
    dest: /etc/hostname
  become: yes
  tags: hostname

- name: set external hostname
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1\t{{ inventory_hostname }}"
  register: hostfile
  become: yes
  tags: hostname

- name: reboot pi
  reboot:
  when: hostfile.changed
  become: yes
  tags: hostname
