---
- name: Add hostname file
  ansible.builtin.template:
    src: hostname.j2
    dest: /etc/hostname
  become: true
  notify:
    - reboot pi
  tags: hostname

- name: Set external hostname  # noqa: no-tabs (the file is formatted with tabs)
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1\t{{ inventory_hostname }}"
  register: hostfile
  become: true
  notify:
    - reboot pi
  tags: hostname
