---
- name: update apt cache
  apt:
    update_cache: yes
  become: yes

- name: upgrade safe packages
  apt:
    upgrade: safe
  become: yes

- name: install essential packages
  apt:
    state: present
    pkg:
      - vim
      - htop
  become: yes

- name: remove unused packages and clean up cache
  apt:
    autoclean: yes
    autoremove: yes
  become: yes

- name: ensure locale exists
  locale_gen:
    name: '{{ locale }}'
    state: present
  become: yes

- name: set default locale
  command: update-locale LANG={{ locale }} LC_ALL={{ locale }} LANGUAGE={{ locale }}
  become: yes
