---
- name: Manage apt packages
  ansible.builtin.import_tasks: packages.yml

- name: Manage dotfiles
  ansible.builtin.import_tasks: dotfiles.yml

- name: Update naming of the host
  ansible.builtin.import_tasks: hostname.yml
