---
# NOTE: ansible module for that is currently broken - run manual
- name: update apt cache
  # command: apt-get update
  apt:
    update_cache: yes
  become: yes
  tags: packages

- name: upgrade distro
  apt:
    upgrade: dist
  become: yes
  tags: packages

- name: upgrade safe packages
  # command: apt-get upgrade -y
  apt:
    upgrade: safe
  become: yes
  tags: packages

- name: install essential packages
  apt:
    state: present
    pkg:
      - vim
      - htop
  become: yes
  tags: packages

- name: remove unused packages and clean up cache
  apt:
    autoclean: yes
    autoremove: yes
  become: yes
  tags: packages

- name: add hostname file
  template:
    src: hostname.j2
    dest: /etc/hostname
  become: yes
  tags: hostname

- name: set external hostname
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1\t{{ inventory_hostname }}"
  become: yes
  tags: hostname

- name: reboot pi
  reboot:
  become: yes
  tags: hostname
