---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true
  tags: packages

- name: Upgrade distro
  ansible.builtin.apt:
    upgrade: dist
  become: true
  tags: packages

- name: Upgrade safe packages
  ansible.builtin.apt:
    upgrade: safe
  become: true
  tags: packages

- name: Install essential packages
  ansible.builtin.apt:
    state: present
    pkg:
      - vim
      - htop
      - jq
  become: true
  tags: packages

- name: Remove unused packages and clean up cache
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
  become: true
  tags: packages
